function(filter_out filter_out_LIST_VAR filter_out_SUBSTRING)
    foreach(filter_out_TMP_PATH ${${filter_out_LIST_VAR}})
        string(FIND ${filter_out_TMP_PATH} ${filter_out_SUBSTRING} filter_out_EXCLUDE_DIR_FOUND)
        if(NOT ${filter_out_EXCLUDE_DIR_FOUND} EQUAL -1)
            list(REMOVE_ITEM ${filter_out_LIST_VAR} ${filter_out_TMP_PATH})
        endif()
    endforeach(filter_out_TMP_PATH)
    set(${filter_out_LIST_VAR} ${${filter_out_LIST_VAR}} PARENT_SCOPE)
endfunction()
